### ISSUE TITLE
无法加载资源文件

### ISSUE THREAD

**Issue by wang316902972** [wj596/go-mysql-transfer#110]
panic: open statics/index.html: no such file or directory

goroutine 1 [running]:
html/template.Must(...)
        /usr/local/src/go/src/html/template/template.go:374
github.com/gin-gonic/gin.(*Engine).LoadHTMLFiles(0xc0001128c0, {0xc000116480, 0x1, 0x1})
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:204 +0x2ec
go-mysql-transfer/web.Start()
        /usr/local/src/go-mysql-transfer/web/router.go:36 +0x165
main.main()
        /usr/local/src/go-mysql-transfer/main.go:132 +0xfc

**Comment by json7** [comment]
本项目不维护了,请换到canal
