### ISSUE TITLE
transfer为什么重启会失败

### ISSUE THREAD

**Issue by chriszhang-dba** [wj596/go-mysql-transfer#33]
问题描述：
在同步数据到es的过程中，transfer进程宕掉之后，再次重启会失败，报错如下：
[root@test transfer]# cat nohup.out 

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 1 [running]:
go-mysql-transfer/service/endpoint.(*Elastic6Endpoint).updateIndexMapping(0xc000350940, 0xc00024aa00, 0xc00003e0a8, 0x301fa01)
	D:/dev/golang/projects/go-mysql-transfer/service/endpoint/elastic6.go:131 +0xa73
go-mysql-transfer/service/endpoint.(*Elastic6Endpoint).indexMapping(0xc000350940, 0xc00003e0a8, 0xc0002636a0)
	D:/dev/golang/projects/go-mysql-transfer/service/endpoint/elastic6.go:79 +0x1bc
go-mysql-transfer/service/endpoint.(*Elastic6Endpoint).Connect(0xc000350940, 0x1eaf5e0, 0xc000350940)
	D:/dev/golang/projects/go-mysql-transfer/service/endpoint/elastic6.go:69 +0x18c
go-mysql-transfer/service.(*TransferService).initialize(0xc0002690a0, 0xc0002690a0, 0xc000080a20)
	D:/dev/golang/projects/go-mysql-transfer/service/transfer_service.go:86 +0x238
go-mysql-transfer/service.Initialize(0x0, 0x0)
	D:/dev/golang/projects/go-mysql-transfer/service/service.go:35 +0x7d
main.main()
	D:/dev/golang/projects/go-mysql-transfer/main.go:121 +0xfe

**Comment by wj596** [comment]
你好，
初步判断应该是更新IndexMapping不成功导致的，我这边没法重现；
建议你先在elasticsearch管理工具中删除这个IndexMapping，在重启下应用试试；
后面版本会对IndexMapping更新模块进行改进：
1、细化日志输出
2、IndexMapping创建和更新操作加固
